// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package feedbackmodule.proxies;

public enum TranslationLanguages
{
	Dutch("1850292c-cb21-40a3-8c3a-daec34b896ca"),
	English("45b5924c-1111-4bfa-ad14-dd4402b4c287"),
	French("12afe3da-a918-4d18-87e7-d0f775a05e06"),
	German("79a9b37c-56e6-40a7-88f6-23c7c29e578a"),
	Hindi("a3470284-5fe5-425d-a5e5-f20cdab6ccc2"),
	Portuguese("57728106-002c-4e54-a1ce-1144d70fe9c5"),
	Spanish("f830c536-5540-42fa-bbd8-ab2ebe370bec"),
	Turkish("bfb1394f-fdb8-471c-b717-71ae7e87bc33");

	private final java.lang.String i18nCaptionKey;
	
	private TranslationLanguages(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
