// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nanoflowcommons.proxies;

public enum GeocodingProvider
{
	Google("3ae56c7c-141c-4eb6-b64d-1b6b115cfc8f"),
	Geocodio("09088c9d-bf15-46f6-9758-c36a385808d7"),
	LocationIQ("c2e39e42-c384-4d57-828b-ba43c76326fc"),
	MapQuest("c5621934-4ed8-4920-86d7-9b58a6690c6c");

	private final java.lang.String i18nCaptionKey;
	
	private GeocodingProvider(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
