// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Empresa implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject empresaMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Empresa";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		RazaoSocial("RazaoSocial"),
		GreenScore("GreenScore"),
		CNPJ("CNPJ"),
		Empresa_Insumo("MyFirstModule.Empresa_Insumo");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Empresa(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Empresa(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject empresaMendixObject)
	{
		if (empresaMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!empresaMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.empresaMendixObject = empresaMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.Empresa initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Empresa(context, mendixObject);
	}

	public static myfirstmodule.proxies.Empresa load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Empresa.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Empresa> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.Empresa.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of RazaoSocial
	 */
	public final java.lang.String getRazaoSocial()
	{
		return getRazaoSocial(getContext());
	}

	/**
	 * @param context
	 * @return value of RazaoSocial
	 */
	public final java.lang.String getRazaoSocial(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.RazaoSocial.toString());
	}

	/**
	 * Set value of RazaoSocial
	 * @param razaosocial
	 */
	public final void setRazaoSocial(java.lang.String razaosocial)
	{
		setRazaoSocial(getContext(), razaosocial);
	}

	/**
	 * Set value of RazaoSocial
	 * @param context
	 * @param razaosocial
	 */
	public final void setRazaoSocial(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String razaosocial)
	{
		getMendixObject().setValue(context, MemberNames.RazaoSocial.toString(), razaosocial);
	}

	/**
	 * @return value of GreenScore
	 */
	public final java.lang.Integer getGreenScore()
	{
		return getGreenScore(getContext());
	}

	/**
	 * @param context
	 * @return value of GreenScore
	 */
	public final java.lang.Integer getGreenScore(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.GreenScore.toString());
	}

	/**
	 * Set value of GreenScore
	 * @param greenscore
	 */
	public final void setGreenScore(java.lang.Integer greenscore)
	{
		setGreenScore(getContext(), greenscore);
	}

	/**
	 * Set value of GreenScore
	 * @param context
	 * @param greenscore
	 */
	public final void setGreenScore(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer greenscore)
	{
		getMendixObject().setValue(context, MemberNames.GreenScore.toString(), greenscore);
	}

	/**
	 * @return value of CNPJ
	 */
	public final java.lang.String getCNPJ()
	{
		return getCNPJ(getContext());
	}

	/**
	 * @param context
	 * @return value of CNPJ
	 */
	public final java.lang.String getCNPJ(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CNPJ.toString());
	}

	/**
	 * Set value of CNPJ
	 * @param cnpj
	 */
	public final void setCNPJ(java.lang.String cnpj)
	{
		setCNPJ(getContext(), cnpj);
	}

	/**
	 * Set value of CNPJ
	 * @param context
	 * @param cnpj
	 */
	public final void setCNPJ(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String cnpj)
	{
		getMendixObject().setValue(context, MemberNames.CNPJ.toString(), cnpj);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Empresa_Insumo
	 */
	public final myfirstmodule.proxies.Insumo getEmpresa_Insumo() throws com.mendix.core.CoreException
	{
		return getEmpresa_Insumo(getContext());
	}

	/**
	 * @param context
	 * @return value of Empresa_Insumo
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.Insumo getEmpresa_Insumo(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Insumo result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Empresa_Insumo.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.Insumo.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Empresa_Insumo
	 * @param empresa_insumo
	 */
	public final void setEmpresa_Insumo(myfirstmodule.proxies.Insumo empresa_insumo)
	{
		setEmpresa_Insumo(getContext(), empresa_insumo);
	}

	/**
	 * Set value of Empresa_Insumo
	 * @param context
	 * @param empresa_insumo
	 */
	public final void setEmpresa_Insumo(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Insumo empresa_insumo)
	{
		if (empresa_insumo == null) {
			getMendixObject().setValue(context, MemberNames.Empresa_Insumo.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Empresa_Insumo.toString(), empresa_insumo.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return empresaMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Empresa that = (myfirstmodule.proxies.Empresa) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
