// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Insumo implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject insumoMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Insumo";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Nome("Nome"),
		Descricao("Descricao"),
		Categoria("Categoria"),
		Quantidade("Quantidade"),
		Pureza("Pureza"),
		PrecoEstimado("PrecoEstimado"),
		Status("Status");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Insumo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Insumo(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject insumoMendixObject)
	{
		if (insumoMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!insumoMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.insumoMendixObject = insumoMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.Insumo initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Insumo(context, mendixObject);
	}

	public static myfirstmodule.proxies.Insumo load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Insumo.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Insumo> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.Insumo.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Nome
	 */
	public final java.lang.String getNome()
	{
		return getNome(getContext());
	}

	/**
	 * @param context
	 * @return value of Nome
	 */
	public final java.lang.String getNome(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Nome.toString());
	}

	/**
	 * Set value of Nome
	 * @param nome
	 */
	public final void setNome(java.lang.String nome)
	{
		setNome(getContext(), nome);
	}

	/**
	 * Set value of Nome
	 * @param context
	 * @param nome
	 */
	public final void setNome(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String nome)
	{
		getMendixObject().setValue(context, MemberNames.Nome.toString(), nome);
	}

	/**
	 * @return value of Descricao
	 */
	public final java.lang.String getDescricao()
	{
		return getDescricao(getContext());
	}

	/**
	 * @param context
	 * @return value of Descricao
	 */
	public final java.lang.String getDescricao(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Descricao.toString());
	}

	/**
	 * Set value of Descricao
	 * @param descricao
	 */
	public final void setDescricao(java.lang.String descricao)
	{
		setDescricao(getContext(), descricao);
	}

	/**
	 * Set value of Descricao
	 * @param context
	 * @param descricao
	 */
	public final void setDescricao(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String descricao)
	{
		getMendixObject().setValue(context, MemberNames.Descricao.toString(), descricao);
	}

	/**
	 * @return value of Categoria
	 */
	public final java.lang.String getCategoria()
	{
		return getCategoria(getContext());
	}

	/**
	 * @param context
	 * @return value of Categoria
	 */
	public final java.lang.String getCategoria(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Categoria.toString());
	}

	/**
	 * Set value of Categoria
	 * @param categoria
	 */
	public final void setCategoria(java.lang.String categoria)
	{
		setCategoria(getContext(), categoria);
	}

	/**
	 * Set value of Categoria
	 * @param context
	 * @param categoria
	 */
	public final void setCategoria(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String categoria)
	{
		getMendixObject().setValue(context, MemberNames.Categoria.toString(), categoria);
	}

	/**
	 * @return value of Quantidade
	 */
	public final java.math.BigDecimal getQuantidade()
	{
		return getQuantidade(getContext());
	}

	/**
	 * @param context
	 * @return value of Quantidade
	 */
	public final java.math.BigDecimal getQuantidade(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Quantidade.toString());
	}

	/**
	 * Set value of Quantidade
	 * @param quantidade
	 */
	public final void setQuantidade(java.math.BigDecimal quantidade)
	{
		setQuantidade(getContext(), quantidade);
	}

	/**
	 * Set value of Quantidade
	 * @param context
	 * @param quantidade
	 */
	public final void setQuantidade(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal quantidade)
	{
		getMendixObject().setValue(context, MemberNames.Quantidade.toString(), quantidade);
	}

	/**
	 * @return value of Pureza
	 */
	public final java.lang.Integer getPureza()
	{
		return getPureza(getContext());
	}

	/**
	 * @param context
	 * @return value of Pureza
	 */
	public final java.lang.Integer getPureza(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Pureza.toString());
	}

	/**
	 * Set value of Pureza
	 * @param pureza
	 */
	public final void setPureza(java.lang.Integer pureza)
	{
		setPureza(getContext(), pureza);
	}

	/**
	 * Set value of Pureza
	 * @param context
	 * @param pureza
	 */
	public final void setPureza(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer pureza)
	{
		getMendixObject().setValue(context, MemberNames.Pureza.toString(), pureza);
	}

	/**
	 * @return value of PrecoEstimado
	 */
	public final java.math.BigDecimal getPrecoEstimado()
	{
		return getPrecoEstimado(getContext());
	}

	/**
	 * @param context
	 * @return value of PrecoEstimado
	 */
	public final java.math.BigDecimal getPrecoEstimado(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.PrecoEstimado.toString());
	}

	/**
	 * Set value of PrecoEstimado
	 * @param precoestimado
	 */
	public final void setPrecoEstimado(java.math.BigDecimal precoestimado)
	{
		setPrecoEstimado(getContext(), precoestimado);
	}

	/**
	 * Set value of PrecoEstimado
	 * @param context
	 * @param precoestimado
	 */
	public final void setPrecoEstimado(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal precoestimado)
	{
		getMendixObject().setValue(context, MemberNames.PrecoEstimado.toString(), precoestimado);
	}

	/**
	 * @return value of Status
	 */
	public final java.lang.String getStatus()
	{
		return getStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of Status
	 */
	public final java.lang.String getStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Status.toString());
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final void setStatus(java.lang.String status)
	{
		setStatus(getContext(), status);
	}

	/**
	 * Set value of Status
	 * @param context
	 * @param status
	 */
	public final void setStatus(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String status)
	{
		getMendixObject().setValue(context, MemberNames.Status.toString(), status);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return insumoMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Insumo that = (myfirstmodule.proxies.Insumo) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
