// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class PerfilUsuario implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject perfilUsuarioMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.PerfilUsuario";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Nome("Nome"),
		PontosGamificacao("PontosGamificacao"),
		Cargo("Cargo");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public PerfilUsuario(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected PerfilUsuario(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject perfilUsuarioMendixObject)
	{
		if (perfilUsuarioMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!perfilUsuarioMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.perfilUsuarioMendixObject = perfilUsuarioMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.PerfilUsuario initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.PerfilUsuario(context, mendixObject);
	}

	public static myfirstmodule.proxies.PerfilUsuario load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.PerfilUsuario.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.PerfilUsuario> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.PerfilUsuario.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Nome
	 */
	public final java.lang.String getNome()
	{
		return getNome(getContext());
	}

	/**
	 * @param context
	 * @return value of Nome
	 */
	public final java.lang.String getNome(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Nome.toString());
	}

	/**
	 * Set value of Nome
	 * @param nome
	 */
	public final void setNome(java.lang.String nome)
	{
		setNome(getContext(), nome);
	}

	/**
	 * Set value of Nome
	 * @param context
	 * @param nome
	 */
	public final void setNome(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String nome)
	{
		getMendixObject().setValue(context, MemberNames.Nome.toString(), nome);
	}

	/**
	 * @return value of PontosGamificacao
	 */
	public final java.lang.Integer getPontosGamificacao()
	{
		return getPontosGamificacao(getContext());
	}

	/**
	 * @param context
	 * @return value of PontosGamificacao
	 */
	public final java.lang.Integer getPontosGamificacao(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.PontosGamificacao.toString());
	}

	/**
	 * Set value of PontosGamificacao
	 * @param pontosgamificacao
	 */
	public final void setPontosGamificacao(java.lang.Integer pontosgamificacao)
	{
		setPontosGamificacao(getContext(), pontosgamificacao);
	}

	/**
	 * Set value of PontosGamificacao
	 * @param context
	 * @param pontosgamificacao
	 */
	public final void setPontosGamificacao(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer pontosgamificacao)
	{
		getMendixObject().setValue(context, MemberNames.PontosGamificacao.toString(), pontosgamificacao);
	}

	/**
	 * @return value of Cargo
	 */
	public final java.lang.String getCargo()
	{
		return getCargo(getContext());
	}

	/**
	 * @param context
	 * @return value of Cargo
	 */
	public final java.lang.String getCargo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Cargo.toString());
	}

	/**
	 * Set value of Cargo
	 * @param cargo
	 */
	public final void setCargo(java.lang.String cargo)
	{
		setCargo(getContext(), cargo);
	}

	/**
	 * Set value of Cargo
	 * @param context
	 * @param cargo
	 */
	public final void setCargo(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String cargo)
	{
		getMendixObject().setValue(context, MemberNames.Cargo.toString(), cargo);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return perfilUsuarioMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.PerfilUsuario that = (myfirstmodule.proxies.PerfilUsuario) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
