// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class RotaLogistica implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject rotaLogisticaMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.RotaLogistica";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Origem("Origem"),
		Destino("Destino"),
		EspacoDisponivel("EspacoDisponivel"),
		DataFrete("DataFrete"),
		RotaLogistica_Transacao("MyFirstModule.RotaLogistica_Transacao");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public RotaLogistica(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected RotaLogistica(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject rotaLogisticaMendixObject)
	{
		if (rotaLogisticaMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!rotaLogisticaMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.rotaLogisticaMendixObject = rotaLogisticaMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.RotaLogistica initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.RotaLogistica(context, mendixObject);
	}

	public static myfirstmodule.proxies.RotaLogistica load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.RotaLogistica.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.RotaLogistica> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.RotaLogistica.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Origem
	 */
	public final java.lang.String getOrigem()
	{
		return getOrigem(getContext());
	}

	/**
	 * @param context
	 * @return value of Origem
	 */
	public final java.lang.String getOrigem(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Origem.toString());
	}

	/**
	 * Set value of Origem
	 * @param origem
	 */
	public final void setOrigem(java.lang.String origem)
	{
		setOrigem(getContext(), origem);
	}

	/**
	 * Set value of Origem
	 * @param context
	 * @param origem
	 */
	public final void setOrigem(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String origem)
	{
		getMendixObject().setValue(context, MemberNames.Origem.toString(), origem);
	}

	/**
	 * @return value of Destino
	 */
	public final java.lang.String getDestino()
	{
		return getDestino(getContext());
	}

	/**
	 * @param context
	 * @return value of Destino
	 */
	public final java.lang.String getDestino(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Destino.toString());
	}

	/**
	 * Set value of Destino
	 * @param destino
	 */
	public final void setDestino(java.lang.String destino)
	{
		setDestino(getContext(), destino);
	}

	/**
	 * Set value of Destino
	 * @param context
	 * @param destino
	 */
	public final void setDestino(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String destino)
	{
		getMendixObject().setValue(context, MemberNames.Destino.toString(), destino);
	}

	/**
	 * @return value of EspacoDisponivel
	 */
	public final java.math.BigDecimal getEspacoDisponivel()
	{
		return getEspacoDisponivel(getContext());
	}

	/**
	 * @param context
	 * @return value of EspacoDisponivel
	 */
	public final java.math.BigDecimal getEspacoDisponivel(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.EspacoDisponivel.toString());
	}

	/**
	 * Set value of EspacoDisponivel
	 * @param espacodisponivel
	 */
	public final void setEspacoDisponivel(java.math.BigDecimal espacodisponivel)
	{
		setEspacoDisponivel(getContext(), espacodisponivel);
	}

	/**
	 * Set value of EspacoDisponivel
	 * @param context
	 * @param espacodisponivel
	 */
	public final void setEspacoDisponivel(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal espacodisponivel)
	{
		getMendixObject().setValue(context, MemberNames.EspacoDisponivel.toString(), espacodisponivel);
	}

	/**
	 * @return value of DataFrete
	 */
	public final java.util.Date getDataFrete()
	{
		return getDataFrete(getContext());
	}

	/**
	 * @param context
	 * @return value of DataFrete
	 */
	public final java.util.Date getDataFrete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.DataFrete.toString());
	}

	/**
	 * Set value of DataFrete
	 * @param datafrete
	 */
	public final void setDataFrete(java.util.Date datafrete)
	{
		setDataFrete(getContext(), datafrete);
	}

	/**
	 * Set value of DataFrete
	 * @param context
	 * @param datafrete
	 */
	public final void setDataFrete(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date datafrete)
	{
		getMendixObject().setValue(context, MemberNames.DataFrete.toString(), datafrete);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of RotaLogistica_Transacao
	 */
	public final myfirstmodule.proxies.Transacao getRotaLogistica_Transacao() throws com.mendix.core.CoreException
	{
		return getRotaLogistica_Transacao(getContext());
	}

	/**
	 * @param context
	 * @return value of RotaLogistica_Transacao
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.Transacao getRotaLogistica_Transacao(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Transacao result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.RotaLogistica_Transacao.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.Transacao.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of RotaLogistica_Transacao
	 * @param rotalogistica_transacao
	 */
	public final void setRotaLogistica_Transacao(myfirstmodule.proxies.Transacao rotalogistica_transacao)
	{
		setRotaLogistica_Transacao(getContext(), rotalogistica_transacao);
	}

	/**
	 * Set value of RotaLogistica_Transacao
	 * @param context
	 * @param rotalogistica_transacao
	 */
	public final void setRotaLogistica_Transacao(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Transacao rotalogistica_transacao)
	{
		if (rotalogistica_transacao == null) {
			getMendixObject().setValue(context, MemberNames.RotaLogistica_Transacao.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.RotaLogistica_Transacao.toString(), rotalogistica_transacao.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return rotaLogisticaMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.RotaLogistica that = (myfirstmodule.proxies.RotaLogistica) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
