// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Transacao implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject transacaoMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Transacao";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ValorFinal("ValorFinal"),
		DataVenda("DataVenda"),
		Tipo("Tipo"),
		Transacao_Insumo("MyFirstModule.Transacao_Insumo"),
		Transacao_Vendedor("MyFirstModule.Transacao_Vendedor");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Transacao(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Transacao(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject transacaoMendixObject)
	{
		if (transacaoMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!transacaoMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.transacaoMendixObject = transacaoMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.Transacao initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Transacao(context, mendixObject);
	}

	public static myfirstmodule.proxies.Transacao load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Transacao.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Transacao> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.Transacao.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of ValorFinal
	 */
	public final java.math.BigDecimal getValorFinal()
	{
		return getValorFinal(getContext());
	}

	/**
	 * @param context
	 * @return value of ValorFinal
	 */
	public final java.math.BigDecimal getValorFinal(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.ValorFinal.toString());
	}

	/**
	 * Set value of ValorFinal
	 * @param valorfinal
	 */
	public final void setValorFinal(java.math.BigDecimal valorfinal)
	{
		setValorFinal(getContext(), valorfinal);
	}

	/**
	 * Set value of ValorFinal
	 * @param context
	 * @param valorfinal
	 */
	public final void setValorFinal(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal valorfinal)
	{
		getMendixObject().setValue(context, MemberNames.ValorFinal.toString(), valorfinal);
	}

	/**
	 * @return value of DataVenda
	 */
	public final java.util.Date getDataVenda()
	{
		return getDataVenda(getContext());
	}

	/**
	 * @param context
	 * @return value of DataVenda
	 */
	public final java.util.Date getDataVenda(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.DataVenda.toString());
	}

	/**
	 * Set value of DataVenda
	 * @param datavenda
	 */
	public final void setDataVenda(java.util.Date datavenda)
	{
		setDataVenda(getContext(), datavenda);
	}

	/**
	 * Set value of DataVenda
	 * @param context
	 * @param datavenda
	 */
	public final void setDataVenda(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date datavenda)
	{
		getMendixObject().setValue(context, MemberNames.DataVenda.toString(), datavenda);
	}

	/**
	 * @return value of Tipo
	 */
	public final java.lang.String getTipo()
	{
		return getTipo(getContext());
	}

	/**
	 * @param context
	 * @return value of Tipo
	 */
	public final java.lang.String getTipo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Tipo.toString());
	}

	/**
	 * Set value of Tipo
	 * @param tipo
	 */
	public final void setTipo(java.lang.String tipo)
	{
		setTipo(getContext(), tipo);
	}

	/**
	 * Set value of Tipo
	 * @param context
	 * @param tipo
	 */
	public final void setTipo(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String tipo)
	{
		getMendixObject().setValue(context, MemberNames.Tipo.toString(), tipo);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Transacao_Insumo
	 */
	public final myfirstmodule.proxies.Insumo getTransacao_Insumo() throws com.mendix.core.CoreException
	{
		return getTransacao_Insumo(getContext());
	}

	/**
	 * @param context
	 * @return value of Transacao_Insumo
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.Insumo getTransacao_Insumo(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Insumo result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Transacao_Insumo.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.Insumo.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Transacao_Insumo
	 * @param transacao_insumo
	 */
	public final void setTransacao_Insumo(myfirstmodule.proxies.Insumo transacao_insumo)
	{
		setTransacao_Insumo(getContext(), transacao_insumo);
	}

	/**
	 * Set value of Transacao_Insumo
	 * @param context
	 * @param transacao_insumo
	 */
	public final void setTransacao_Insumo(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Insumo transacao_insumo)
	{
		if (transacao_insumo == null) {
			getMendixObject().setValue(context, MemberNames.Transacao_Insumo.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Transacao_Insumo.toString(), transacao_insumo.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Transacao_Vendedor
	 */
	public final myfirstmodule.proxies.Empresa getTransacao_Vendedor() throws com.mendix.core.CoreException
	{
		return getTransacao_Vendedor(getContext());
	}

	/**
	 * @param context
	 * @return value of Transacao_Vendedor
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.Empresa getTransacao_Vendedor(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Empresa result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Transacao_Vendedor.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.Empresa.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Transacao_Vendedor
	 * @param transacao_vendedor
	 */
	public final void setTransacao_Vendedor(myfirstmodule.proxies.Empresa transacao_vendedor)
	{
		setTransacao_Vendedor(getContext(), transacao_vendedor);
	}

	/**
	 * Set value of Transacao_Vendedor
	 * @param context
	 * @param transacao_vendedor
	 */
	public final void setTransacao_Vendedor(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Empresa transacao_vendedor)
	{
		if (transacao_vendedor == null) {
			getMendixObject().setValue(context, MemberNames.Transacao_Vendedor.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Transacao_Vendedor.toString(), transacao_vendedor.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return transacaoMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Transacao that = (myfirstmodule.proxies.Transacao) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
