// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package webactions.proxies;

public enum PictureQuality
{
	original("4eea6d4e-8c1a-4cb5-8f7c-87fd4f596dc5"),
	low("65228b85-e668-4147-a22d-22a1ce9f7312"),
	medium("6a0a0cab-6b04-489f-a3c8-7f1f29427986"),
	high("b3ed0f8e-c513-4de6-9c1b-12f374f7b4fb"),
	custom("f17a631e-dfd8-4cdd-9678-9a1114bf33b9");

	private final java.lang.String i18nCaptionKey;
	
	private PictureQuality(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
