// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datawidgets.proxies;

public enum Filter_Operators
{
	contains("9963051d-e1aa-4379-bed8-40bf487bfb27"),
	startsWith("4e440b19-4144-4ef0-996e-ce5b7ea55ed9"),
	endsWith("de342d60-e90f-4ab0-ba8f-5b66e6d8f332"),
	between("494aa85b-68eb-4df1-9fc2-3d47f87d0817"),
	greater("ccec8631-4d3d-401a-ae76-ca4647baa234"),
	greaterEqual("056b9a49-ce79-4d4c-aea9-c6d847bff1f8"),
	equal("ca054457-de1c-44ca-801a-7b2278b900c4"),
	notEqual("00f0076d-0cca-4bbd-b3bf-8d0d7a4f797f"),
	smaller("3d6ea47e-9f2a-4577-a3c5-c93fe342590d"),
	smallerEqual("9c913d68-80ca-4304-aeb0-9f782244a962"),
	empty("dc94ee47-4b7d-46c9-878c-0faee7c30382"),
	notEmpty("1b83504f-f159-4b6b-ac2b-f797d1b3fca6");

	private final java.lang.String i18nCaptionKey;
	
	private Filter_Operators(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
